"""Write docs/dimensions.md from the rubric catalogue, propensity/rubrics/dimensions.yaml.

Run it after adding or updating a dimension; the test suite fails while the page is stale.

    python docs/make_dimensions.py
"""

from pathlib import Path

from propensity.annotation.rubrics import (
    available_versions,
    check_rubric,
    load_dimensions,
    load_rubric,
)

HERE = Path(__file__).resolve().parent


def rubric_link(code, version):
    return f"[{version}](../propensity/rubrics/{code}/{code}_{version}.md)"


def render() -> str:
    catalogue = load_dimensions()
    codes = sorted(catalogue, key=str.lower)
    lines = [
        "# Dimensions",
        "",
        "<!-- Generated by docs/make_dimensions.py from propensity/rubrics/dimensions.yaml. "
        "Do not edit by hand. -->",
        "",
        f"PROPEL ships {len(codes)} dimensions, each with its own rubric. Pass the code as "
        "`--dimension`; the trait name and the rubric version below are used unless you override "
        "them. To add or update one: [Managing rubrics](managing-rubrics.md).",
        "",
        "| Code | Trait, as the prompt words it | −3 | +3 | Current | All versions |",
        "|---|---|---|---|---|---|",
    ]
    for code in codes:
        entry = catalogue[code]
        versions = ", ".join(rubric_link(code, version) for version in available_versions(code))
        lines.append(f"| `{code}` | {entry.name} | {entry.negative} | {entry.positive} | "
                     f"{rubric_link(code, entry.version)} | {versions} |")

    lines += ["", "## What each measures", ""]
    lines += [f"- **`{code}`** ({catalogue[code].name}): {catalogue[code].summary}" for code in codes]

    lines += [
        "",
        "## Structure checks",
        "",
        "The result of `check_rubric` on each current rubric ([required structure]"
        "(rubrics.md#rubric-structure)). Gaps in a version that has produced data stay in that "
        "version, and are fixed in the next one.",
        "",
        "| Code | Version | Result |",
        "|---|---|---|",
    ]
    for code in codes:
        version = catalogue[code].version
        problems = check_rubric(load_rubric(code, version=version))
        result = "passes" if not problems else "; ".join(problems)
        lines.append(f"| `{code}` | {version} | {result} |")
    return "\n".join(lines) + "\n"


def main():
    path = HERE / "dimensions.md"
    path.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
